### ISSUE TITLE
Update User Experience

### ISSUE THREAD

**Issue by han-so1omon** [icon-community/CPS#81]
## Overview

Update the User Experience of the CPS for voters, developers, and viewers

## Story

As a voter, I want to have a clear way to evaluate project performance and conformance, as well as establish community targets, so that I can appropriately establish incentivization and accountability, as well as provide effective feedback

As a developer, I want to have a clear way to demonstrate my progress and view community targets so that I can get good feedback and capitalize on incentivization pathways for good projects. I also want to be sure that my project is sustainable in the long term, so that the project remains useful after the CPS contract is completed

As a viewer, I want to have a clear way to understand the state of projects and community targets so that I can provide effective feedback

**Comment by CyrusVorwald** [comment]
In the CPS wiki https://github.com/icon-community/CPS/wiki/Applicant-Flow#execution-and-progress-reports, it says "All approved Contribution Proposals are expected to execute the project in accordance with the original proposal and are expected to start work upon receiving payment of the first installment." It also says "Once a proposal is approved, funds will be released in the form of monthly installments, with the first installment being paid at the end of the Voting Period in which its first progress report was approved."

Currently, the way someone adds milestones to their project proposal is in the image below. In my opinion, changing the milestones duration from "Month" to a specific date would be helpful because after a project proposal gets approved, that project only has 2 weeks to submit a progress report, not 1 month. Alternatively, calculating what date things are due by based on the input duration would help because currently I do not actually know when my milestone is due as it is not explicitly stated anywhere.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/90732384/211371377-5990e926-5e87-4c90-a6cc-fd8b9783ad02.png">
